version: "3.8"
services:
  webgoat:
    build:
      context: .
      dockerfile: Dockerfile
    image: webgoat-contrast
    ports:
      - "8080:8080"
    environment:
      CONTRAST__API__URL: "${CONTRAST__API__URL}"
      CONTRAST__API__API_KEY: "${CONTRAST__API__API_KEY}"
      CONTRAST__API__SERVICE_KEY: "${CONTRAST__API__SERVICE_KEY}"
      CONTRAST__API__USER_NAME: "${CONTRAST__API__USER_NAME}"
      CONTRAST__APPLICATION__NAME: "${CONTRAST__APPLICATION__NAME}"
      CONTRAST__AGENT__JAVA__STANDALONE_APP_NAME: "${CONTRAST__APPLICATION__NAME}"

      